environment: production
environmentCode:
name: ffc-pay-alerting
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-alerting

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-alerting-config-map

containerSecret:
  name: ffc-pay-alerting-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  messageQueueHost: namespace.servicebus.windows.net
  alertTopicAddress: ffc-pay-alert
  alertSubscriptionAddress: ffc-pay-alerting
  notifyApiKey:
  sendAlerts: true
  azureStorageConnectionString: dummy
  azureStorageAccountName: ffcpay
  storageContainer: dax
  inboundFolder: inbound
  archiveFolder: archive
  quarantineFolder: quarantine
  returnFolder: return
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-pay-alerting

postgresService:
  postgresDb: ffc_pay_alerting
  postgresqlHost: ffc-pay-alerting-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres
  logging: false

readinessProbe:
  path: /healthy
  port: 3008
  initialDelaySeconds: 60
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

livenessProbe:
  path: /healthz
  port: 3008
  initialDelaySeconds: 70
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
