name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-10d54-2

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-alerting-env-var
    pr_params:
      container.notifyApiKey: ${{ eq(variables['pr_notifyApiKey'], 'true') }}
    snd2_params:
      container.notifyApiKey: ${{ eq(variables['snd2_notifyApiKey'], 'true') }}
    dev_params:
      container.notifyApiKey: ${{ eq(variables['dev_notifyApiKey'], 'true') }}
    test_params:
      container.notifyApiKey: ${{ eq(variables['test_notifyApiKey'], 'true') }}
    pre_params:
      container.notifyApiKey: ${{ eq(variables['pre_notifyApiKey'], 'true') }}
    prd_params:
      container.notifyApiKey: ${{ eq(variables['prd_notifyApiKey'], 'true') }}
