name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-10d54-2

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-alerting-env-var
    pr_params:
      container.sendAlerts: $(pr_sendAlerts)
      container.notifyApiKey: $(pr_notifyApiKey)
      container.devTeamEmails: $(pr_devTeamEmails)
      container.pdsTeamEmails: $(pr_pdsTeamEmails)
    snd2_params:
      container.sendAlerts: $(snd2_sendAlerts)
      container.notifyApiKey: $(snd2_notifyApiKey)
      container.devTeamEmails: $(snd2_devTeamEmails)
      container.pdsTeamEmails: $(snd2_pdsTeamEmails)
    dev_params:
      container.sendAlerts: $(dev_sendAlerts)
      container.notifyApiKey: $(dev_notifyApiKey)
      container.devTeamEmails: $(dev_devTeamEmails)
      container.pdsTeamEmails: $(dev_pdsTeamEmails)
    test_params:
      container.sendAlerts: $(test_sendAlerts)
      container.notifyApiKey: $(test_notifyApiKey)
      container.devTeamEmails: $(test_devTeamEmails)
      container.pdsTeamEmails: $(test_pdsTeamEmails)
    pre_params:
      container.sendAlerts: $(pre_sendAlerts)
      container.notifyApiKey: $(pre_notifyApiKey)
      container.devTeamEmails: $(pre_devTeamEmails)
      container.pdsTeamEmails: $(pre_pdsTeamEmails)
    prd_params:
      container.sendAlerts: $(prd_sendAlerts)
      container.notifyApiKey: $(prd_notifyApiKey)
      container.devTeamEmails: $(prd_devTeamEmails)
      container.pdsTeamEmails: $(prd_pdsTeamEmails)
