name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-10d54-2

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-alerting-env-var
    pr_params:
      container.notifyApiKey: $('pr_notifyApiKey')
    snd2_params:
      container.notifyApiKey: $('snd2_notifyApiKey')
    dev_params:
      container.notifyApiKey: $('dev_notifyApiKey')
    test_params:
      container.notifyApiKey: $('test_notifyApiKey')
    pre_params:
      container.notifyApiKey: $('pre_notifyApiKey')
    prd_params:
      container.notifyApiKey: $('prd_notifyApiKey')
