services:
  ffc-pay-alerting:
    build:
      context: .
      target: production
    image: ffc-pay-alerting
    container_name: ffc-pay-alerting
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-alerting-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
