const db = require('../data')

const addContact = async (payload) => {
  const {
    emailAddress,
    addedBy,
    BATCH_REJECTED,
    BATCH_QUARANTINED,
    PAYMENT_REJECTED,
    PAYMENT_DAX_REJECTED,
    PAYMENT_INVALID_BANK,
    PAYMENT_PROCESSING_FAILED,
    PAYMENT_SETTLEMENT_UNSETTLED,
    PAYMENT_SETTLEMENT_UNMATCHED,
    RESPONSE_REJECTED,
    PAYMENT_REQUEST_BLOCKED,
    PAYMENT_DAX_UNAVAILABLE,
    RECEIVER_CONNECTION_FAILED,
    DEMOGRAPHICS_PROCESSING_FAILED,
    DEMOGRAPHICS_UPDATE_FAILED,
    EVENT_SAVE_ALERT,
    TABLE_CREATE_ALERT
  } = payload

  await db.contact.create({
    emailAddress,
    addedBy,
    addedAt: Date.now(),
    BATCH_REJECTED,
    BATCH_QUARANTINED,
    PAYMENT_REJECTED,
    PAYMENT_DAX_REJECTED,
    PAYMENT_INVALID_BANK,
    PAYMENT_PROCESSING_FAILED,
    PAYMENT_SETTLEMENT_UNSETTLED,
    PAYMENT_SETTLEMENT_UNMATCHED,
    RESPONSE_REJECTED,
    PAYMENT_REQUEST_BLOCKED,
    PAYMENT_DAX_UNAVAILABLE,
    RECEIVER_CONNECTION_FAILED,
    DEMOGRAPHICS_PROCESSING_FAILED,
    DEMOGRAPHICS_UPDATE_FAILED,
    EVENT_SAVE_ALERT,
    TABLE_CREATE_ALERT
  })
}

module.exports = {
  addContact
}
