const {
  SFI,
  SFIP,
  LUMP_SUMS,
  VET_VISITS,
  CS,
  BPS,
  MANUAL,
  ES,
  FC,
  IMPS,
  SFI23,
  DELINKED,
  SFI_EXPANDED,
  COHTR,
  COHTC,
  FPTT,
  WMP,
  SFI26
} = require('./schemes')

module.exports = {
  [SFI]: 'SFI22',
  [SFIP]: 'SFI Pilot',
  [LUMP_SUMS]: 'Lump Sums',
  [VET_VISITS]: 'Annual Health and Welfare Review',
  [CS]: 'Countryside Stewardship',
  [BPS]: 'BPS',
  [MANUAL]: 'Manual Invoice',
  [ES]: 'Environmental Stewardship',
  [FC]: 'Forestry Commission',
  [IMPS]: 'IMPS',
  [SFI23]: 'SFI23',
  [DELINKED]: 'Delinked Payments',
  [SFI_EXPANDED]: 'Expanded SFI Offer',
  [COHTR]: 'Combined Offer Higher Tier Revenue',
  [COHTC]: 'Combined Offer Higher Tier Capital',
  [FPTT]: 'Farm Payments Technical Test',
  [WMP]: 'Woodland Management Plan',
  [SFI26]: 'SFI26'
}
