module.exports = {
  BATCH_REJECTED: '678abf78-463b-414b-ab47-f40fca95f650',
  BATCH_QUARANTINED: '',
  PAYMENT_REJECTED: '',
  PAYMENT_DAX_REJECTED: '',
  PAYMENT_INVALID_BANK: '',
  PAYMENT_PROCESSING_FAILED: '',
  PAYMENT_SETTLEMENT_UNMATCHED: '',
  RESPONSE_REJECTED: '',
  PAYMENT_REQUEST_BLOCKED: ''
}
